// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class EntertainmentProduct
    {
        public string EntertainmentId { get; set; }
        public string ProductId { get; set; }
        public string ShowId { get; set; }
        public string GameId { get; set; }
        public decimal? EntertainmentProductPrice { get; set; }
        public int? Quantity { get; set; }

        public virtual Entertainment Entertainment { get; set; }
        public virtual GameServices Game { get; set; }
        public virtual ShowService Show { get; set; }
    }
}