// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class EventBooker
    {
        public EventBooker()
        {
            ChatMessage = new HashSet<ChatMessage>();
            Event = new HashSet<Event>();
            Family = new HashSet<Family>();
            Feedback = new HashSet<Feedback>();
        }

        public string EventBookerId { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public DateTime? RegisterDate { get; set; }
        public bool? Gender { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Image { get; set; }
        public bool Status { get; set; }

        public virtual Account EventBookerNavigation { get; set; }
        public virtual ICollection<ChatMessage> ChatMessage { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<Family> Family { get; set; }
        public virtual ICollection<Feedback> Feedback { get; set; }
    }
}