// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Event
    {
        public Event()
        {
            DateTimeLocation = new HashSet<DateTimeLocation>();
            Feedback = new HashSet<Feedback>();
            Notification = new HashSet<Notification>();
            Payment = new HashSet<Payment>();
            Verify = new HashSet<Verify>();
            Voucher = new HashSet<Voucher>();
        }

        public string EventId { get; set; }
        public string ScriptId { get; set; }
        public string DecorationId { get; set; }
        public string EventTypeId { get; set; }
        public string MenuId { get; set; }
        public string EntertainmentId { get; set; }
        public string EventBookerId { get; set; }
        public string OrganizedPerson { get; set; }
        public DateTime StartDate { get; set; }
        public decimal TotalPrice { get; set; }
        public DateTime EndDate { get; set; }
        public bool Status { get; set; }

        public virtual Decoration Decoration { get; set; }
        public virtual Entertainment Entertainment { get; set; }
        public virtual EventBooker EventBooker { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Script Script { get; set; }
        public virtual ICollection<DateTimeLocation> DateTimeLocation { get; set; }
        public virtual ICollection<Feedback> Feedback { get; set; }
        public virtual ICollection<Notification> Notification { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual ICollection<Verify> Verify { get; set; }
        public virtual ICollection<Voucher> Voucher { get; set; }
    }
}