// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Food
    {
        public Food()
        {
            MenuProduct = new HashSet<MenuProduct>();
        }

        public string FoodId { get; set; }
        public string FoodName { get; set; }
        public string Dish { get; set; }
        public decimal FoodPrice { get; set; }
        public string FoodDescription { get; set; }
        public string FoodIngredient { get; set; }
        public string FoodOrigin { get; set; }
        public string CookingRecipe { get; set; }
        public string FoodImage { get; set; }
        public string FoodTypeId { get; set; }
        public bool Status { get; set; }

        public virtual FoodType FoodType { get; set; }
        public virtual ICollection<MenuProduct> MenuProduct { get; set; }
    }
}