// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class GameServices
    {
        public GameServices()
        {
            EntertainmentProduct = new HashSet<EntertainmentProduct>();
        }

        public string GameId { get; set; }
        public string GameName { get; set; }
        public decimal GameServicePrice { get; set; }
        public string GameDetails { get; set; }
        public string GameRules { get; set; }
        public string GameReward { get; set; }
        public string Supplies { get; set; }
        public string GameImage { get; set; }
        public bool Status { get; set; }

        public virtual ICollection<EntertainmentProduct> EntertainmentProduct { get; set; }
    }
}