// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class MenuProduct
    {
        public string MenuId { get; set; }
        public string Product { get; set; }
        public int Quatity { get; set; }
        public decimal Price { get; set; }
        public bool Type { get; set; }

        public virtual Menu Menu { get; set; }
        public virtual Food ProductNavigation { get; set; }
    }
}