// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Menu
    {
        public Menu()
        {
            Event = new HashSet<Event>();
            MenuProduct = new HashSet<MenuProduct>();
        }

        public string MenuId { get; set; }
        public string MenuName { get; set; }
        public bool Status { get; set; }
        public decimal PriceTotal { get; set; }
        public int? TableQuantity { get; set; }

        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<MenuProduct> MenuProduct { get; set; }
    }
}