// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Participant
    {
        public double PhoneParticipant { get; set; }
        public string FullNameParticipant { get; set; }
        public string Relation { get; set; }
        public string EventId { get; set; }

        public virtual Event Event { get; set; }
    }
}