// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Product
    {
        public Product()
        {
            DecorationProduct = new HashSet<DecorationProduct>();
        }

        public string ProductId { get; set; }
        public string DecorationProductName { get; set; }
        public decimal ProductPrice { get; set; }
        public int ProductQuantity { get; set; }
        public string ProductDetails { get; set; }
        public string ProductImage { get; set; }
        public string ProductSupplier { get; set; }
        public bool Status { get; set; }

        public virtual ICollection<DecorationProduct> DecorationProduct { get; set; }
    }
}