// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Script
    {
        public Script()
        {
            Event = new HashSet<Event>();
        }

        public string Id { get; set; }
        public string ScriptName { get; set; }
        public bool Status { get; set; }
        public string ScriptContent { get; set; }

        public virtual ICollection<Event> Event { get; set; }
    }
}