// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Verify
    {
        public int VerifyId { get; set; }
        public string VerifyCode { get; set; }
        public string EventId { get; set; }

        public virtual Event Event { get; set; }
    }
}